grpc:
  server:
    port: 9091  # grpc服务监听端口

spring:
  application:
    name: matrix-auth-grpc-provider
  main:
    web-application-type: none
  r2dbc:
    url: r2dbc:postgresql://in-server.homemart.club:30432/matrix_db
    username: tooljet
    password: tKqNd7bvDXXpZTC34rL6
    properties:
      schema: matrix
  cloud:
    kubernetes:
      discovery:
        enabled: true
        service-labels:
          app.kubernetes.io/part-of: matrix
  data:
    redis:
      host: in-server.homemart.club
      port: 30363
      password: catadmin1 # 如果有密码

logging:
  level:
    club.hm.matrix: DEBUG
    io.grpc: DEBUG
    org.springframework.data.r2dbc: DEBUG
    root: INFO