grpc:
  server:
    port: 9091  # grpc服务监听端口

spring:
  application:
    name: matrix-auth-grpc-provider
  main:
    web-application-type: none
  cloud:
    kubernetes:
      discovery:
        enabled: true
        service-labels:
          app.kubernetes.io/part-of: matrix
  data:
    redis:
      host: 127.0.0.1
      port: 36379
      password: test # 如果有密码
  r2dbc:
    url: r2dbc:postgresql://127.0.0.1:35432/matrix_db
    username: testuser
    password: testpass
    properties:
      schema: matrix
logging:
  level:
    io.osins.matrix: DEBUG
    io.grpc: DEBUG
    org.springframework.data.r2dbc: DEBUG
    root: INFO