server:
  port: 9091
  
grpc:
  server:
    port: 9090  # grpc服务监听端口

spring:
  r2dbc:
    url: r2dbc:postgresql://in-server.homemart.club:30432/matrix_db
    username: tooljet
    password: tKqNd7bvDXXpZTC34rL6
