spring:
  application:
    name: matrix-gateway
  cloud:
    kubernetes:
      discovery:
        enabled: true
        all-namespaces: false
        service-labels:
          app.kubernetes.io/part-of: matrix
      config:
        enabled: true
        namespace: matrix-system
    gateway:
      server:
        webflux:
          routes:
            - id: matrix-user-service
              uri: lb://matrix-user
              predicates:
                - Path=/api/users/**
            - id: matrix-auth-service
              uri: lb://matrix-auth
              predicates:
                - Path=/api/auth/**

management:
  endpoints:
    web:
      exposure:
        include: health,info,discovery