snowflake-id:
  generator:
    datacenter-id: -1  # 数据中心ID，-1表示自动生成
    machine-id: -1     # 机器ID，-1表示自动生成
    buffer-size: 1000  # 缓冲区大小

logging:
  level:
    io.osins.matrix: DEBUG
    io.grpc: DEBUG
    org.springframework.data.r2dbc: DEBUG
    root: INFO
