spring:
  main:
    web-application-type: none
  cloud:
    kubernetes:
      discovery:
        enabled: false

local:
  grpc:
    service-ports:
      matrix-auth: localhost:9091
      matrix-user: localhost:9092
      matrix-room: localhost:9093
      matrix-message: localhost:9094
      matrix-websocket: localhost:9095
